// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: GameInfo.proto

#include <GRPC/GameInfo.pb.h>
#include <GRPC/GameInfo.grpc.pb.h>

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace IvionOnline {

static const char* CardDatabaseService_method_names[] = {
  "/IvionOnline.CardDatabaseService/RetrieveCardData",
};

std::unique_ptr< CardDatabaseService::Stub> CardDatabaseService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CardDatabaseService::Stub> stub(new CardDatabaseService::Stub(channel));
  return stub;
}

CardDatabaseService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RetrieveCardData_(CardDatabaseService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CardDatabaseService::Stub::RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::IvionOnline::CardData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IvionOnline::CardInfo, ::IvionOnline::CardData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RetrieveCardData_, context, request, response);
}

void CardDatabaseService::Stub::experimental_async::RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IvionOnline::CardInfo, ::IvionOnline::CardData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RetrieveCardData_, context, request, response, std::move(f));
}

void CardDatabaseService::Stub::experimental_async::RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RetrieveCardData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>* CardDatabaseService::Stub::PrepareAsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IvionOnline::CardData, ::IvionOnline::CardInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RetrieveCardData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>* CardDatabaseService::Stub::AsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRetrieveCardDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

CardDatabaseService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardDatabaseService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardDatabaseService::Service, ::IvionOnline::CardInfo, ::IvionOnline::CardData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardDatabaseService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IvionOnline::CardInfo* req,
             ::IvionOnline::CardData* resp) {
               return service->RetrieveCardData(ctx, req, resp);
             }, this)));
}

CardDatabaseService::Service::~Service() {
}

::grpc::Status CardDatabaseService::Service::RetrieveCardData(::grpc::ServerContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IvionOnline

