// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: GameInfo.proto
#ifndef GRPC_GameInfo_2eproto__INCLUDED
#define GRPC_GameInfo_2eproto__INCLUDED

#include <GRPC/GameInfo.pb.h>

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace IvionOnline {

class CardDatabaseService final {
 public:
  static constexpr char const* service_full_name() {
    return "IvionOnline.CardDatabaseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::IvionOnline::CardData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>> AsyncRetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>>(AsyncRetrieveCardDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>> PrepareAsyncRetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>>(PrepareAsyncRetrieveCardDataRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>* AsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IvionOnline::CardData>* PrepareAsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::IvionOnline::CardData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>> AsyncRetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>>(AsyncRetrieveCardDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>> PrepareAsyncRetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>>(PrepareAsyncRetrieveCardDataRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RetrieveCardData(::grpc::ClientContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>* AsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::IvionOnline::CardData>* PrepareAsyncRetrieveCardDataRaw(::grpc::ClientContext* context, const ::IvionOnline::CardInfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RetrieveCardData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RetrieveCardData(::grpc::ServerContext* context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RetrieveCardData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRetrieveCardData(::grpc::ServerContext* context, ::IvionOnline::CardInfo* request, ::grpc::ServerAsyncResponseWriter< ::IvionOnline::CardData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RetrieveCardData<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RetrieveCardData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::IvionOnline::CardInfo, ::IvionOnline::CardData>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::IvionOnline::CardInfo* request, ::IvionOnline::CardData* response) { return this->RetrieveCardData(context, request, response); }));}
    void SetMessageAllocatorFor_RetrieveCardData(
        ::grpc::experimental::MessageAllocator< ::IvionOnline::CardInfo, ::IvionOnline::CardData>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::IvionOnline::CardInfo, ::IvionOnline::CardData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RetrieveCardData(
      ::grpc::CallbackServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RetrieveCardData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RetrieveCardData<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RetrieveCardData<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RetrieveCardData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RetrieveCardData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRetrieveCardData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RetrieveCardData() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RetrieveCardData(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RetrieveCardData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RetrieveCardData(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RetrieveCardData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RetrieveCardData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::IvionOnline::CardInfo, ::IvionOnline::CardData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::IvionOnline::CardInfo, ::IvionOnline::CardData>* streamer) {
                       return this->StreamedRetrieveCardData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RetrieveCardData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RetrieveCardData(::grpc::ServerContext* /*context*/, const ::IvionOnline::CardInfo* /*request*/, ::IvionOnline::CardData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRetrieveCardData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::IvionOnline::CardInfo,::IvionOnline::CardData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RetrieveCardData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RetrieveCardData<Service > StreamedService;
};

}  // namespace IvionOnline


#endif  // GRPC_GameInfo_2eproto__INCLUDED
