# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GameInfo.proto',
  package='NetworkIO',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eGameInfo.proto\x12\tNetworkIO\"\xa5\x01\n\x04\x43\x61rd\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x11\n\tArchetype\x18\x02 \x01(\t\x12\r\n\x05\x43ount\x18\x03 \x01(\x05\x12\x10\n\x08Ultimate\x18\x04 \x01(\x08\x12\x0c\n\x04\x46\x65\x61t\x18\x05 \x01(\x08\x12 \n\x06\x43olors\x18\x06 \x03(\x0e\x32\x10.NetworkIO.Color\x12\x13\n\x0bPlayEffects\x18\x07 \x01(\x0c\x12\x16\n\x0eResolveEffects\x18\x08 \x01(\x0c\"l\n\x08\x44\x65\x63kList\x12!\n\x08Ultimate\x18\x01 \x01(\x0b\x32\x0f.NetworkIO.Card\x12\x1e\n\x05\x46\x65\x61ts\x18\x02 \x03(\x0b\x32\x0f.NetworkIO.Card\x12\x1d\n\x04\x44\x65\x63k\x18\x03 \x03(\x0b\x32\x0f.NetworkIO.Card\"\r\n\x0bRandomAgent\"\t\n\x07\x41IAgent\"\x1f\n\x0bPlayerAgent\x12\x10\n\x08PlayerID\x18\x01 \x01(\x05\"\x1d\n\x05Vec2i\x12\t\n\x01X\x18\x01 \x01(\x05\x12\t\n\x01Y\x18\x02 \x01(\x05\"\x8c\x02\n\nPlayerInfo\x12\x10\n\x08Username\x18\x01 \x01(\t\x12\x0b\n\x03UID\x18\x02 \x01(\t\x12!\n\x04\x44\x65\x63k\x18\x03 \x01(\x0b\x32\x13.NetworkIO.DeckList\x12*\n\x10StartingPosition\x18\x04 \x01(\x0b\x32\x10.NetworkIO.Vec2i\x12%\n\x07\x41IAgent\x18\x05 \x01(\x0b\x32\x12.NetworkIO.AIAgentH\x00\x12-\n\x0bRandomAgent\x18\x06 \x01(\x0b\x32\x16.NetworkIO.RandomAgentH\x00\x12-\n\x0bPlayerAgent\x18\x07 \x01(\x0b\x32\x16.NetworkIO.PlayerAgentH\x00\x42\x0b\n\tAgentInfo\"U\n\x08GameInfo\x12&\n\x07Players\x18\x01 \x03(\x0b\x32\x15.NetworkIO.PlayerInfo\x12!\n\x07MapSize\x18\x02 \x01(\x0b\x32\x10.NetworkIO.Vec2i*E\n\x05\x43olor\x12\x08\n\x04GRAY\x10\x00\x12\t\n\x05\x42LACK\x10\x01\x12\x07\n\x03RED\x10\x02\x12\t\n\x05GREEN\x10\x03\x12\x08\n\x04\x42LUE\x10\x04\x12\t\n\x05WHITE\x10\x05\x62\x06proto3'
)

_COLOR = _descriptor.EnumDescriptor(
  name='Color',
  full_name='NetworkIO.Color',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GRAY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=755,
  serialized_end=824,
)
_sym_db.RegisterEnumDescriptor(_COLOR)

Color = enum_type_wrapper.EnumTypeWrapper(_COLOR)
GRAY = 0
BLACK = 1
RED = 2
GREEN = 3
BLUE = 4
WHITE = 5



_CARD = _descriptor.Descriptor(
  name='Card',
  full_name='NetworkIO.Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='NetworkIO.Card.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Archetype', full_name='NetworkIO.Card.Archetype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Count', full_name='NetworkIO.Card.Count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Ultimate', full_name='NetworkIO.Card.Ultimate', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Feat', full_name='NetworkIO.Card.Feat', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Colors', full_name='NetworkIO.Card.Colors', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PlayEffects', full_name='NetworkIO.Card.PlayEffects', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ResolveEffects', full_name='NetworkIO.Card.ResolveEffects', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=195,
)


_DECKLIST = _descriptor.Descriptor(
  name='DeckList',
  full_name='NetworkIO.DeckList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ultimate', full_name='NetworkIO.DeckList.Ultimate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Feats', full_name='NetworkIO.DeckList.Feats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Deck', full_name='NetworkIO.DeckList.Deck', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=305,
)


_RANDOMAGENT = _descriptor.Descriptor(
  name='RandomAgent',
  full_name='NetworkIO.RandomAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=320,
)


_AIAGENT = _descriptor.Descriptor(
  name='AIAgent',
  full_name='NetworkIO.AIAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=331,
)


_PLAYERAGENT = _descriptor.Descriptor(
  name='PlayerAgent',
  full_name='NetworkIO.PlayerAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlayerID', full_name='NetworkIO.PlayerAgent.PlayerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=364,
)


_VEC2I = _descriptor.Descriptor(
  name='Vec2i',
  full_name='NetworkIO.Vec2i',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='NetworkIO.Vec2i.X', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Y', full_name='NetworkIO.Vec2i.Y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=395,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='NetworkIO.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Username', full_name='NetworkIO.PlayerInfo.Username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UID', full_name='NetworkIO.PlayerInfo.UID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Deck', full_name='NetworkIO.PlayerInfo.Deck', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StartingPosition', full_name='NetworkIO.PlayerInfo.StartingPosition', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AIAgent', full_name='NetworkIO.PlayerInfo.AIAgent', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RandomAgent', full_name='NetworkIO.PlayerInfo.RandomAgent', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PlayerAgent', full_name='NetworkIO.PlayerInfo.PlayerAgent', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='AgentInfo', full_name='NetworkIO.PlayerInfo.AgentInfo',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=398,
  serialized_end=666,
)


_GAMEINFO = _descriptor.Descriptor(
  name='GameInfo',
  full_name='NetworkIO.GameInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Players', full_name='NetworkIO.GameInfo.Players', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MapSize', full_name='NetworkIO.GameInfo.MapSize', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=753,
)

_CARD.fields_by_name['Colors'].enum_type = _COLOR
_DECKLIST.fields_by_name['Ultimate'].message_type = _CARD
_DECKLIST.fields_by_name['Feats'].message_type = _CARD
_DECKLIST.fields_by_name['Deck'].message_type = _CARD
_PLAYERINFO.fields_by_name['Deck'].message_type = _DECKLIST
_PLAYERINFO.fields_by_name['StartingPosition'].message_type = _VEC2I
_PLAYERINFO.fields_by_name['AIAgent'].message_type = _AIAGENT
_PLAYERINFO.fields_by_name['RandomAgent'].message_type = _RANDOMAGENT
_PLAYERINFO.fields_by_name['PlayerAgent'].message_type = _PLAYERAGENT
_PLAYERINFO.oneofs_by_name['AgentInfo'].fields.append(
  _PLAYERINFO.fields_by_name['AIAgent'])
_PLAYERINFO.fields_by_name['AIAgent'].containing_oneof = _PLAYERINFO.oneofs_by_name['AgentInfo']
_PLAYERINFO.oneofs_by_name['AgentInfo'].fields.append(
  _PLAYERINFO.fields_by_name['RandomAgent'])
_PLAYERINFO.fields_by_name['RandomAgent'].containing_oneof = _PLAYERINFO.oneofs_by_name['AgentInfo']
_PLAYERINFO.oneofs_by_name['AgentInfo'].fields.append(
  _PLAYERINFO.fields_by_name['PlayerAgent'])
_PLAYERINFO.fields_by_name['PlayerAgent'].containing_oneof = _PLAYERINFO.oneofs_by_name['AgentInfo']
_GAMEINFO.fields_by_name['Players'].message_type = _PLAYERINFO
_GAMEINFO.fields_by_name['MapSize'].message_type = _VEC2I
DESCRIPTOR.message_types_by_name['Card'] = _CARD
DESCRIPTOR.message_types_by_name['DeckList'] = _DECKLIST
DESCRIPTOR.message_types_by_name['RandomAgent'] = _RANDOMAGENT
DESCRIPTOR.message_types_by_name['AIAgent'] = _AIAGENT
DESCRIPTOR.message_types_by_name['PlayerAgent'] = _PLAYERAGENT
DESCRIPTOR.message_types_by_name['Vec2i'] = _VEC2I
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
DESCRIPTOR.message_types_by_name['GameInfo'] = _GAMEINFO
DESCRIPTOR.enum_types_by_name['Color'] = _COLOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.Card)
  })
_sym_db.RegisterMessage(Card)

DeckList = _reflection.GeneratedProtocolMessageType('DeckList', (_message.Message,), {
  'DESCRIPTOR' : _DECKLIST,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.DeckList)
  })
_sym_db.RegisterMessage(DeckList)

RandomAgent = _reflection.GeneratedProtocolMessageType('RandomAgent', (_message.Message,), {
  'DESCRIPTOR' : _RANDOMAGENT,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.RandomAgent)
  })
_sym_db.RegisterMessage(RandomAgent)

AIAgent = _reflection.GeneratedProtocolMessageType('AIAgent', (_message.Message,), {
  'DESCRIPTOR' : _AIAGENT,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.AIAgent)
  })
_sym_db.RegisterMessage(AIAgent)

PlayerAgent = _reflection.GeneratedProtocolMessageType('PlayerAgent', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERAGENT,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.PlayerAgent)
  })
_sym_db.RegisterMessage(PlayerAgent)

Vec2i = _reflection.GeneratedProtocolMessageType('Vec2i', (_message.Message,), {
  'DESCRIPTOR' : _VEC2I,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.Vec2i)
  })
_sym_db.RegisterMessage(Vec2i)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERINFO,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.PlayerInfo)
  })
_sym_db.RegisterMessage(PlayerInfo)

GameInfo = _reflection.GeneratedProtocolMessageType('GameInfo', (_message.Message,), {
  'DESCRIPTOR' : _GAMEINFO,
  '__module__' : 'GameInfo_pb2'
  # @@protoc_insertion_point(class_scope:NetworkIO.GameInfo)
  })
_sym_db.RegisterMessage(GameInfo)


# @@protoc_insertion_point(module_scope)
